// <auto-generated />
using System;
using Company_SD.Db_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company_SD.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20241015185246_EmpHasSuperVisor")]
    partial class EmpHasSuperVisor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company_SD.Entities.Department", b =>
                {
                    b.Property<int>("DNum")
                        .HasColumnType("int");

                    b.Property<string>("DName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("MrgSSN")
                        .HasColumnType("int");

                    b.Property<DateTime?>("hireDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DNum");

                    b.HasIndex("MrgSSN")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Company_SD.Entities.Dependent", b =>
                {
                    b.Property<int>("DName")
                        .HasColumnType("int");

                    b.Property<int>("SSN")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("DName", "SSN");

                    b.HasIndex("SSN");

                    b.ToTable("Dependent");
                });

            modelBuilder.Entity("Company_SD.Entities.Employee", b =>
                {
                    b.Property<int>("SSN")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DBDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DNo")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LName")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("SuperId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("SSN");

                    b.HasIndex("DNo");

                    b.HasIndex("SuperId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Company_SD.Entities.Location", b =>
                {
                    b.Property<int>("DNum")
                        .HasColumnType("int");

                    b.Property<string>("Loc")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("DNum", "Loc");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Company_SD.Entities.Project", b =>
                {
                    b.Property<int>("PNum")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("DNum")
                        .HasColumnType("int");

                    b.Property<string>("Loc")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("PName")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("PNum");

                    b.HasIndex("DNum");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Company_SD.Entities.Work", b =>
                {
                    b.Property<int>("SSN")
                        .HasColumnType("int");

                    b.Property<int>("PNumber")
                        .HasColumnType("int");

                    b.Property<int?>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsPNum")
                        .HasColumnType("int");

                    b.HasKey("SSN", "PNumber");

                    b.HasIndex("ProjectsPNum");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("Company_SD.Entities.Department", b =>
                {
                    b.HasOne("Company_SD.Entities.Employee", "OtherEmployees")
                        .WithOne("OtherDepartments")
                        .HasForeignKey("Company_SD.Entities.Department", "MrgSSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OtherEmployees");
                });

            modelBuilder.Entity("Company_SD.Entities.Dependent", b =>
                {
                    b.HasOne("Company_SD.Entities.Employee", "Employees")
                        .WithMany("Dependents")
                        .HasForeignKey("SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Company_SD.Entities.Employee", b =>
                {
                    b.HasOne("Company_SD.Entities.Department", "Departments")
                        .WithMany("Employees")
                        .HasForeignKey("DNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Company_SD.Entities.Employee", "Employees")
                        .WithMany("SuperVisor")
                        .HasForeignKey("SuperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Company_SD.Entities.Location", b =>
                {
                    b.HasOne("Company_SD.Entities.Department", "Departments")
                        .WithMany("Locations")
                        .HasForeignKey("DNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Company_SD.Entities.Project", b =>
                {
                    b.HasOne("Company_SD.Entities.Department", "Departments")
                        .WithMany("Projects")
                        .HasForeignKey("DNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Company_SD.Entities.Work", b =>
                {
                    b.HasOne("Company_SD.Entities.Project", null)
                        .WithMany("Works")
                        .HasForeignKey("ProjectsPNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company_SD.Entities.Employee", null)
                        .WithMany("Works")
                        .HasForeignKey("SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company_SD.Entities.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Locations");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Company_SD.Entities.Employee", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("OtherDepartments")
                        .IsRequired();

                    b.Navigation("SuperVisor");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("Company_SD.Entities.Project", b =>
                {
                    b.Navigation("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
